version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: sysacad-db
    environment:
      POSTGRES_DB: SysAcadDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-test-db.sql:/docker-entrypoint-initdb.d/init-test-db.sql
    restart: unless-stopped

volumes:
  postgres_data: